language: python

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda create --yes -n pymdmix python=$TRAVIS_PYTHON_VERSION
  - source activate pymdmix

  # Below, include the dependencies you want to install with conda, optionally
  # specifying versions used in the matrix above. If you split this into
  # multiple conda install commands, you should always include numpy=$NUMPY as
  # the first package to install (for every conda install command) otherwise
  # numpy may be automatically upgraded.

  - conda install -y -c omnia openmm=7.2.1 mdtraj parmed=3.0.1
  - conda install -y -c ambermd ambertools
  - conda install -y -c bioconda biskit
  - conda install -y -c scipy matplotlib

  # You can also install some dependencies with pip if not available in conda

  # - pip install ...

script:

  - source /home/travis/miniconda2/envs/pymdmix/amber.sh
  - python setup.py install
  - mdmix -h
  - python pyMDMix/test.py all


